Controllers/ChatController.cs
namespace Ndumiso_Assessment_2023_05_17.Controllers
{    
    using System.Net.Http;
    using System.Text;

    using FluentValidation;
    using FluentValidation.Results;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;

    using Ndumiso_Assessment_2023_05_17.Interfaces;
    using Ndumiso_Assessment_2023_05_17.Models;
    using Ndumiso_Assessment_2023_05_17.Validators;
    using Newtonsoft.Json;

    public class ChatController : Controller
    {
        private readonly IChatService chatService;
        private readonly IHttpClientFactory httpClientFactory;
        private readonly IValidator<Chat> questionValidator;
        private readonly IMemoryCache memoryCache;

        public ChatController(IHttpClientFactory httpClientFactory, IValidator<Chat> questionValidator, IMemoryCache memoryCache, IChatService chatService)
        {
            this.httpClientFactory = httpClientFactory;
            this.questionValidator = questionValidator;
            this.memoryCache = memoryCache;
            this.chatService = chatService;
        }

        [Authorize]
        public async Task<IActionResult> Index(Chat model)
        {
            ValidationResult result = questionValidator.Validate(model);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View();
            }

            if(model.UserQuestion != null && model.Answer != null)
            {
                ViewBag.Question = model.UserQuestion;
                ViewBag.Response = model.Answer;

                return View();
            }

            var chatCache = memoryCache.Get<Chat>(model.UserQuestion);

            if (chatCache != null && chatCache.UserQuestion == model.UserQuestion)
            {
                ViewBag.Question = chatCache.UserQuestion;
                ViewBag.Response = chatCache.Answer;

                return View();
            }

            var question = model.UserQuestion;
            var response = await ChatResponse(question);

            if (response != null)
            {
                var chat = new Chat();
                
                chat.CreatedAt = DateTime.Now;
                chat.UserQuestion = question;
                chat.Answer = response;

                memoryCache.Set(chat.UserQuestion, chat, TimeSpan.FromDays(1));
                
                chatService.Add(chat);
            }

            ViewBag.Question = question;
            ViewBag.Response = response;

            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Details(int Id)
        {
            var chat = chatService.GetById(Id);

            if (chat == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", chat);
        }

        public async Task<string> ChatResponse(string question)
        {
            string errorString;

            try
            {
                var httpClient = httpClientFactory.CreateClient("OpenAI");

                var requestBodyObject = new
                {
                    model = "text-davinci-003",
                    prompt = question,
                    max_tokens = 50
                };

                var requestBody = JsonConvert.SerializeObject(requestBodyObject);

                var content = new StringContent(requestBody, Encoding.UTF8, "application/json");

                var response = await httpClient.PostAsync("completions", content);

                if (response.IsSuccessStatusCode)
                {
                    var jsonResponse = await response.Content.ReadAsStringAsync();
                    var responseObject = JsonConvert.DeserializeObject<dynamic>(jsonResponse);
                    var responseText = responseObject.choices[0].text.ToString();

                    return responseText;
                }
                else
                {
                    return $"There was an error retrieving the response: {response.StatusCode.ToString()}";
                }

            }
            catch (Exception e)
            {
                errorString = $"There was an error retrieving the response: {e.Message}";

            }

            return errorString;
        }
    }
}

Controllers/ImageController.cs
namespace Ndumiso_Assessment_2023_05_17.Controllers
{
    using System;
    using System.Net.Http;
    using System.Text;

    using FluentValidation;
    using FluentValidation.Results;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;

    using Ndumiso_Assessment_2023_05_17.Interfaces;
    using Ndumiso_Assessment_2023_05_17.Models;
    using Ndumiso_Assessment_2023_05_17.Services;
    using Ndumiso_Assessment_2023_05_17.Validators;
    using Newtonsoft.Json;


    public class ImageController : Controller
    {
        private readonly IImageService imageService;
        private readonly IHttpClientFactory httpClientFactory;
        private readonly IValidator<Image> imageValidator;
        private readonly IMemoryCache memoryCache;

        public ImageController(IHttpClientFactory httpClientFactory, IValidator<Image> imageValidator, IMemoryCache memoryCache, IImageService imageService)
        {
            this.httpClientFactory = httpClientFactory;
            this.imageValidator = imageValidator;
            this.memoryCache = memoryCache;
            this.imageService = imageService;
        }

        [Authorize]
        public async Task<IActionResult> Index(Image model)
        {
            ValidationResult result = imageValidator.Validate(model);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);
                return View();
            }

            if (model.Description != null && model.Url != null)
            {
                ViewBag.Description = model.Description;
                ViewBag.Response = model.Url;

                return View();
            }

            var imageCache = memoryCache.Get<Image>(model.Description);

            if (imageCache != null && imageCache.Description == model.Description)
            {
                ViewBag.Description = imageCache.Description;
                ViewBag.Response = imageCache.Url;

                return View();
            }

            var request = model.Description;
            var response = await GenerateImage(request);

            if (response != null)
            {
                var image = new Image();
                
                image.CreatedAt = DateTime.Now;
                image.Description = request;
                image.Url = response;

                memoryCache.Set(request, image, TimeSpan.FromDays(1));

                imageService.Add(image);
            }

            ViewBag.Description = request;
            ViewBag.Response = response;

            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Details(int Id)
        {
            var image = imageService.GetById(Id);

            if (image == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", image);
        }

        public async Task<string> GenerateImage(string request)
        {
            string errorString;

            try
            {
                var httpClient = httpClientFactory.CreateClient("OpenAI");

                var requestBodyObject = new
                {
                    prompt = request,
                    size = "512x512"
                };

                var requestBody = JsonConvert.SerializeObject(requestBodyObject);

                var content = new StringContent(requestBody, Encoding.UTF8, "application/json");

                var response = await httpClient.PostAsync("images/generations", content);

                if (response.IsSuccessStatusCode)
                {
                    var jsonResponse = await response.Content.ReadAsStringAsync();
                    var responseObject = JsonConvert.DeserializeObject<dynamic>(jsonResponse);
                    var responseText = responseObject.data[0].url.ToString();

                    return responseText;
                }
                else
                {
                    return $"There was an error retrieving the response: {response.StatusCode.ToString()}";
                }

            }
            catch (Exception e)
            {
                errorString = $"There was an error retrieving the response: {e.Message}";

            }

            return errorString;
        }
    }
}

Controllers/TextEditingController.cs
namespace Ndumiso_Assessment_2023_05_17.Controllers
{
    using System;
    using System.Net.Http;
    using System.Text;

    using FluentValidation;
    using FluentValidation.Results;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;

    using Ndumiso_Assessment_2023_05_17.Interfaces;
    using Ndumiso_Assessment_2023_05_17.Models;
    using Ndumiso_Assessment_2023_05_17.Services;
    using Ndumiso_Assessment_2023_05_17.Validators;
    using Newtonsoft.Json;

    public class TextEditingController : Controller
    {
        private readonly ITextService textService;
        private readonly IHttpClientFactory httpClientFactory;
        private readonly IValidator<Text> textValidator;
        private readonly IMemoryCache memoryCache;

        public TextEditingController(IHttpClientFactory httpClientFactory, IValidator<Text> textValidator, IMemoryCache memoryCache, ITextService textService)
        {
            this.httpClientFactory = httpClientFactory;
            this.textValidator = textValidator;
            this.memoryCache = memoryCache;
            this.textService = textService;
        }

        [Authorize]
        public async Task<IActionResult> Index(Text model)
        {
            ValidationResult result = textValidator.Validate(model);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return View();
            }

            if (model.UserText != null && model.Answer != null)
            {
                ViewBag.Text = $"{model.Task}:  {model.UserText}";
                ViewBag.Response = model.Answer;

                return View();
            }

            var textCache = memoryCache.Get<Text>(model.UserText);

            if (textCache != null && textCache.UserText == model.UserText && textCache.Task == model.Task)
            {
                ViewBag.Text = $"{textCache.Task}:  {textCache.UserText}";
                ViewBag.Response = textCache.Answer;

                return View();
            }

            var text = model.UserText;

            var instructionText = "";

            switch (model.Task)
            {
                case "Check Spelling":
                    instructionText = "Fix the spelling mistakes";
                    break;
                case "Paraphrase":
                    instructionText = "paraphrase";
                    break;
                case "Translate to English":
                    instructionText = "Translate to English";
                    break;
            }

            var response = await EditText(text, instructionText);

            if(response != null) 
            {
                var textObject = new Text();

                textObject.CreatedAt = DateTime.Now;
                textObject.UserText = text;
                textObject.Task = model.Task;
                textObject.Answer = response;

                memoryCache.Set(textObject.UserText, textObject, TimeSpan.FromDays(1));

                textService.Add(textObject);
            }

            ViewBag.Text = $"{model.Task}:  {text}";
            ViewBag.Response = response;

            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Details(int Id)
        {
            var text = textService.GetById(Id);

            if (text == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", text);
        }

        public async Task<string> EditText(string text, string command)
        {
            string errorString;

            try
            {
                var httpClient = httpClientFactory.CreateClient("OpenAI");

                var requestBodyObject = new
                {
                    model = "text-davinci-edit-001",
                    input = text,
                    instruction = command
                };

                var requestBody = JsonConvert.SerializeObject(requestBodyObject);

                var content = new StringContent(requestBody, Encoding.UTF8, "application/json");

                var response = await httpClient.PostAsync("edits", content);

                if (response.IsSuccessStatusCode)
                {
                    var jsonResponse = await response.Content.ReadAsStringAsync();
                    var responseObject = JsonConvert.DeserializeObject<dynamic>(jsonResponse);
                    var responseText = responseObject.choices[0].text.ToString();

                    return responseText;
                }
                else
                {
                    return $"There was an error retrieving the response: {response.StatusCode.ToString()}";
                }

            }
            catch (Exception e)
            {
                errorString = $"There was an error retrieving the response: {e.Message}";

            }

            return errorString;
        }
    }
}

Views/Shared/_DevExtremeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Open AI</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    @* Uncomment to use the HtmlEditor control *@
    @* <script src="https://unpkg.com/devextreme-quill@22_2/dist/dx-quill.min.js"></script> *@

    @* Uncomment to use the Gantt control *@
    @*<link href="~/css/devextreme/dx-gantt.css" rel="stylesheet" />*@

    @* Uncomment to use the Diagram control *@
    @*<link href="~/css/devextreme/dx-diagram.css" rel="stylesheet" />*@

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />

    @* Predefined themes: https://js.devexpress.com/DevExtreme/Guide/Themes_and_Styles/Predefined_Themes/ *@
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />

    @* Uncomment to use the Gantt control *@
    @*<script src="~/js/devextreme/dx-gantt.js"></script>*@

    @* Uncomment to use the Diagram control *@
    @*<script src="~/js/devextreme/dx-diagram.js"></script>*@

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    @* Uncomment to use Globalize for localization *@
    @* Docs: https://docs.devexpress.com/AspNetCore/400577#globalize *@
    @*<script src="~/js/devextreme/cldr.js"></script>*@
    @*<script src="~/js/devextreme/cldr/event.js"></script>*@
    @*<script src="~/js/devextreme/cldr/supplemental.js"></script>*@
    @*<script src="~/js/devextreme/cldr/unresolved.js"></script>*@
    @*<script src="~/js/devextreme/globalize.js"></script>*@
    @*<script src="~/js/devextreme/globalize/message.js"></script>*@
    @*<script src="~/js/devextreme/globalize/number.js"></script>*@
    @*<script src="~/js/devextreme/globalize/currency.js"></script>*@
    @*<script src="~/js/devextreme/globalize/date.js"></script>*@

    @* Uncomment to enable client-side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>

    @* Uncomment to provide geo-data for the VectorMap control *@
    @* Docs: https://js.devexpress.com/DevExtreme/Guide/Widgets/VectorMap/Providing_Data/#Data_for_Areas *@
    @*<script src="~/js/devextreme/vectormap-data/world.js"></script>*@

    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
</head>

<body style="padding-top: 5rem;">

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Open AI</a>

            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navbar" class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Chat" asp-action="Index">Chat</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="TextEditing" asp-action="Index">Edit Text</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Image" asp-action="Index">Generate Image</a>
                    </li>
                </ul>
            </div>
            <partial name="_LoginPartial" />
        </div>
    </nav>

    <main class="container">
        @RenderBody()
    </main>
</body>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ndumiso_Assessment_2023_05_17</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ndumiso_Assessment_2023_05_17.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ndumiso_Assessment_2023_05_17</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Ndumiso_Assessment_2023_05_17 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>